### ISSUE TITLE
Data won't load into the website

### ISSUE THREAD

**Issue by whatisaname** [Androz2091/discord-data-package-explorer#33] opened 2021-06-08 14:46 UTC
![dNaYF8Gn](https://user-images.githubusercontent.com/35542342/121206709-b2534680-c846-11eb-929c-6c77472cfb37.png)

There's a lot of folders that can't be read, and I don't know what the error means either.

**Comment by WonderfulDay0** [comment] 2021-06-08 21:56
This is likely similar to https://github.com/Androz2091/discord-data-package-explorer/issues/32

Please check if the messages directory has a messages.csv file in each channel directory (in messages/<channel_id>. It appears Discord has not sent this in the data package for multiple data packages this month (that I know of).

**Comment by Androz2091** [comment] 2021-06-10 16:42
Duplicate of #34

**Closed by Androz2091** 2021-06-10 16:42 UTC
